name: Setup pages

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies.
        run: |
          sudo apt-get install -y pandoc

      - name: Run the tool.
        run: |
          sh ./tool -r

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
